version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "news-2000"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ygkmypp6iac9"
s3_prefix = "news-2000"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
